### ISSUE TITLE
Icon + Input (easy mode!)

### ISSUE THREAD

**Issue by brunoocasali** [brunoocasali/tw-portfolio#4]
Tentar usar a forma de input mais top, usando um ícone + input. sem usar o prepend lá.

css:

``` css
.form-control {
  padding-left: 35px;
}

.form-control + .glyphicon {
  position: absolute;
  left: 0;
  padding: 14px 28px;
}
```
